# Generated by Django 4.2.30 on 2026-05-02 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoicenumbersequence_invoice_inventory_deducted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
