# Generated by Django 4.2.30 on 2026-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_type_alter_invoice_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_of_measure',
            field=models.CharField(default='pcs', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_category',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(default='pcs', max_length=50),
        ),
    ]
