# Generated by Django 4.2.30 on 2026-05-06 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_currencies(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    rows = [
        ("USD", "US Dollar", "$", 2),
        ("EUR", "Euro", "€", 2),
        ("GBP", "British Pound", "£", 2),
        ("JPY", "Japanese Yen", "¥", 0),
        ("CAD", "Canadian Dollar", "$", 2),
        ("AUD", "Australian Dollar", "$", 2),
        ("CHF", "Swiss Franc", "CHF", 2),
        ("CNY", "Chinese Yuan", "¥", 2),
        ("NZD", "New Zealand Dollar", "$", 2),
        ("SEK", "Swedish Krona", "kr", 2),
        ("NOK", "Norwegian Krone", "kr", 2),
    ]
    for code, name, symbol, decimals in rows:
        Currency.objects.update_or_create(
            code=code,
            defaults={"name": name, "symbol": symbol, "decimal_places": decimals},
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('decimal_places', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_code', models.CharField(max_length=10)),
                ('quote_code', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=40)),
                ('number_format', models.CharField(default='1,234.56', max_length=40)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('invoice_template', models.JSONField(blank=True, default=dict)),
                ('receipt_template', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='global', max_length=20, unique=True)),
                ('tax_configuration', models.JSONField(blank=True, default=dict)),
                ('appearance', models.JSONField(blank=True, default=dict)),
                ('allow_user_overrides', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_code', 'quote_code'), name='uniq_fx_pair'),
        ),
        migrations.RunPython(seed_currencies, migrations.RunPython.noop),
    ]
