# Generated by Django 4.2.30 on 2026-06-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_logo_assets_and_settings_links'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialauthconnection',
            new_name='core_social_user_id_7984c0_idx',
            old_name='core_social_user_id_61c5dc_idx',
        ),
        migrations.RenameIndex(
            model_name='socialauthconnection',
            new_name='core_social_provide_6f0764_idx',
            old_name='core_social_provide_12ba57_idx',
        ),
    ]
