# Generated by Django 4.2.30 on 2026-06-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_adminuserinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("fixed", "Fixed amount")],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
