# Generated by Django 4.2.30 on 2026-06-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_invoice_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_restock_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_deleted', 'name'], name='core_custom_is_dele_853681_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_deleted', 'email'], name='core_custom_is_dele_ca95f7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_deleted', 'created_at'], name='core_custom_is_dele_877879_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_deleted', 'invoice_number'], name='core_invoic_is_dele_0f96fe_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_deleted', 'status'], name='core_invoic_is_dele_a32bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'issue_date'], name='core_invoic_custome_d2b710_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'due_date'], name='core_invoic_custome_8b8789_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_deleted', 'total_amount'], name='core_invoic_is_dele_2ba22a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_deleted', 'sku'], name='core_item_is_dele_aed123_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_deleted', 'name'], name='core_item_is_dele_a2b443_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_deleted', 'type'], name='core_item_is_dele_a65cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_deleted', 'stock_quantity'], name='core_item_is_dele_4447b1_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_deleted', 'last_restock_date'], name='core_item_is_dele_5f9dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['is_deleted', 'payment_date'], name='core_receip_is_dele_80c48d_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['invoice', 'payment_date'], name='core_receip_invoice_32c691_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment_method', 'payment_date'], name='core_receip_payment_cb5fab_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['reference_number'], name='core_receip_referen_e1ce32_idx'),
        ),
    ]
