# Generated by Django 4.2.30 on 2026-07-03 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_item_last_restock_date_item_warehouse_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='cost_center',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='policy_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='policy_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('review_required', 'Review required'), ('non_compliant', 'Non-compliant')], default='compliant', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='project_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/expenses/receipts/'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'expense_date'], name='core_expens_is_dele_592483_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'category'], name='core_expens_is_dele_92e382_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'approval_status'], name='core_expens_is_dele_848c01_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'policy_status'], name='core_expens_is_dele_14abe1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'assigned_to'], name='core_expens_is_dele_2e42ce_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'project_code'], name='core_expens_is_dele_83e96e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'cost_center'], name='core_expens_is_dele_31d23e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'created_at'], name='core_expens_is_dele_3df729_idx'),
        ),
    ]
