# Generated by Django 4.2.30 on 2026-07-04 14:37

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_encrypt_expense_sensitive_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=core.models.saved_document_upload_to)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('storage_backend', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_documents', to='core.invoice')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_documents', to='core.receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'document_type', 'created_at'], name='core_savedd_user_id_2745a7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='saveddocument',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('invoice__isnull', False), ('receipt__isnull', True)), models.Q(('invoice__isnull', True), ('receipt__isnull', False)), _connector='OR'), name='chk_saved_document_one_document'),
        ),
    ]
