# Generated by Django 4.2.30 on 2026-07-23 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_project_code_sequence_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAccountDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_account_created_at', models.DateTimeField(editable=False)),
                ('deposited_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_account_deposits', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.sourceaccount')),
            ],
            options={
                'ordering': ('-deposited_at', '-id'),
                'indexes': [models.Index(fields=['source_account', 'deposited_at'], name='core_src_dep_acct_dt_idx')],
            },
        ),
    ]
