"""
Django settings for pixelhub project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import secrets
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

_DEFAULT_INSECURE_SECRET_KEY = secrets.token_urlsafe(64) if DEBUG else ""
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or _DEFAULT_INSECURE_SECRET_KEY
if not DEBUG and (
    not SECRET_KEY
    or len(SECRET_KEY) < 50
):
    raise RuntimeError("DJANGO_SECRET_KEY must be set to a long random value (>= 50 chars) when DJANGO_DEBUG=0")

if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0", "[::1]"]
else:
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "sevalla.app", "").split(",") if h.strip()]
    if not ALLOWED_HOSTS:
        raise RuntimeError("DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG=0 (comma-separated)")

if DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "0") == "1"
    SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "0") == "1"
    CSRF_COOKIE_SECURE = os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "0") == "1"
else:
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "1") == "1"
    SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "1") == "1"
    CSRF_COOKIE_SECURE = os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "1") == "1"
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "1") == "1"
    SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "1") == "1"
    if os.environ.get("DJANGO_SECURE_PROXY_SSL_HEADER", "1") == "1":
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
        USE_X_FORWARDED_HOST = os.environ.get("DJANGO_USE_X_FORWARDED_HOST", "1") == "1"

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get("DJANGO_SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "pixelhub.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "pixelhub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get("POSTGRES_DB") or os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", ""),
            "USER": os.environ.get("POSTGRES_USER", ""),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

REDIS_URL = os.environ.get("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": int(os.environ.get("DJANGO_CACHE_TIMEOUT", "300")),
            "KEY_PREFIX": os.environ.get("DJANGO_CACHE_KEY_PREFIX", "pixelhub"),
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "pixelhub-cache",
        }
    }

EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND", "").strip()
if not EMAIL_BACKEND:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" if os.environ.get("DJANGO_EMAIL_HOST") else "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "1") == "1"
EMAIL_USE_SSL = os.environ.get("DJANGO_EMAIL_USE_SSL", "0") == "1"
EMAIL_TIMEOUT = int(os.environ.get("DJANGO_EMAIL_TIMEOUT", "15"))

DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "no-reply@pixelhub.local")
SERVER_EMAIL = os.environ.get("DJANGO_SERVER_EMAIL", DEFAULT_FROM_EMAIL)

if not DEBUG and EMAIL_BACKEND.endswith("console.EmailBackend") and os.environ.get("DJANGO_ALLOW_CONSOLE_EMAIL_IN_PROD", "0") != "1":
    raise RuntimeError("Email is not configured for production. Set DJANGO_EMAIL_BACKEND and SMTP settings (DJANGO_EMAIL_HOST, DJANGO_EMAIL_HOST_USER, DJANGO_EMAIL_HOST_PASSWORD).")

if not DEBUG and EMAIL_BACKEND.endswith("smtp.EmailBackend") and not EMAIL_HOST:
    raise RuntimeError("DJANGO_EMAIL_HOST must be set when using django.core.mail.backends.smtp.EmailBackend")

FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://127.0.0.1:3000")
BACKEND_PUBLIC_BASE_URL = os.environ.get("BACKEND_PUBLIC_BASE_URL", "http://127.0.0.1:8000")
REGISTRATION_CAPTCHA_BYPASS = os.environ.get("REGISTRATION_CAPTCHA_BYPASS", "0") == "1"
GOOGLE_OAUTH_CLIENT_ID = (os.environ.get("DJANGO_GOOGLE_OAUTH_CLIENT_ID") or os.environ.get("GOOGLE_OAUTH_CLIENT_ID") or "").strip()
GOOGLE_OAUTH_CLIENT_SECRET = (os.environ.get("DJANGO_GOOGLE_OAUTH_CLIENT_SECRET") or os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET") or "").strip()
GITHUB_OAUTH_CLIENT_ID = (os.environ.get("DJANGO_GITHUB_OAUTH_CLIENT_ID") or os.environ.get("GITHUB_OAUTH_CLIENT_ID") or "").strip()
GITHUB_OAUTH_CLIENT_SECRET = (os.environ.get("DJANGO_GITHUB_OAUTH_CLIENT_SECRET") or os.environ.get("GITHUB_OAUTH_CLIENT_SECRET") or "").strip()

PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY", "").strip()
FLUTTERWAVE_SECRET_KEY = os.environ.get("FLUTTERWAVE_SECRET_KEY", "").strip()
FLUTTERWAVE_WEBHOOK_SECRET_HASH = os.environ.get("FLUTTERWAVE_WEBHOOK_SECRET_HASH", "").strip()

OPAY_ENV = os.environ.get("OPAY_ENV", "test").strip()
OPAY_MERCHANT_ID = os.environ.get("OPAY_MERCHANT_ID", "").strip()
OPAY_PRIVATE_KEY = os.environ.get("OPAY_PRIVATE_KEY", "").strip()

BANK_TRANSFER_WEBHOOK_SECRET = os.environ.get("BANK_TRANSFER_WEBHOOK_SECRET", "").strip()
BANK_TRANSFER_RECONCILIATION_URL = os.environ.get("BANK_TRANSFER_RECONCILIATION_URL", "").strip()
BANK_TRANSFER_RECONCILIATION_SECRET = os.environ.get("BANK_TRANSFER_RECONCILIATION_SECRET", "").strip()


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles"))
MEDIA_URL = os.environ.get("DJANGO_MEDIA_URL", "/media/")
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media"))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

_DEFAULT_CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3002",
    "http://localhost:3003",
    "http://localhost:3004",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3002",
    "http://127.0.0.1:3003",
    "http://127.0.0.1:3004",
]
if DEBUG:
    CORS_ALLOWED_ORIGINS = _DEFAULT_CORS_ALLOWED_ORIGINS
else:
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
        if o.strip()
    ]
    if not CORS_ALLOWED_ORIGINS:
        raise RuntimeError("DJANGO_CORS_ALLOWED_ORIGINS must be set when DJANGO_DEBUG=0 (comma-separated)")

CORS_ALLOW_HEADERS = list(default_headers) + [
    "idempotency-key",
    "merchantid",
    "requesttimestamp",
    "x-paystack-signature",
    "flutterwave-signature",
    "verif-hash",
    "x-bank-transfer-secret",
]

LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        }
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.CookieAccessTokenAuthentication",
        "core.authentication.AccessTokenAuthentication",
    ),
}

API_PAGE_SIZE = int(os.environ.get("API_PAGE_SIZE", "25"))

REQUIRE_PDF = os.environ.get("REQUIRE_PDF", "0") == "1"
if REQUIRE_PDF and not DEBUG:
    try:
        from weasyprint import HTML

        HTML(string="<html><body>ok</body></html>").write_pdf()
    except Exception as e:
        raise RuntimeError(f"PDF rendering is required but WeasyPrint is unavailable: {e.__class__.__name__}") from e
